name: Check Markdown links

on:
  push:
  schedule:
    - cron: '0 0 */15 * *'

jobs:
  markdown-link-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    - name: Run mdl
      uses: actionshub/markdownlint@master
      with:
        path: manuscript
